flowchart BT

subgraph pmain ["cmd/chesseract"]

	main["func main()"]

end

main --> chesseract
main --> web-server
main --> web-config
main --> sqlbackend
main --> renderer
main --> gameui
main --> gamestuff
main --> win31

subgraph backends["internal/storage/sql"]
	sqlbackend[Backend]
end

subgraph plumbing ["internal/web-plumbing"]
	%% direction LR
	web-server[Server]
	web-config[Config]
end

plumbing --> web

subgraph web ["web"]
	%% direction LR
	HomeHandler
	MatchHandler
end

web --> chesseract
web --> gamestuff

subgraph chesseract
	%% direction LR
	Match
	Board
	Piece
end

subgraph gamestuff ["chesseract/game"]
	%% direction LR
	Player
	Game
end

gamestuff --> chesseract


subgraph renderer ["internal/renderer"]
	%% direction LR
	Model
	AnimationManager
end

renderer --> Game

subgraph ui ["internal/ui"]
	%% direction LR
	Layer
	EventTarget
	Layout
end

subgraph win31 ["internal/ui/themes"]
	%% direction LR
	Theme
end

Theme --> ui

subgraph gameui ["internal/ui/gameui"]
	%% direction LR
	DialogLayer
	%% MenuLayer
	OSDLayer
	%% DebugLayer
end

OSDLayer --> ui

gameui --> renderer
gameui --> gamestuff
